### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-chef#1]
- [x] add deployment key to repo so we can pull automatically (and/or make repo public)
- [ ] setup secrets repo and make chef pull from that for apache keys, db passwords, etc.
- [x] mariadb chef support
- [x] web deployment script
- [x] handle static user generated content
- [ ] share documentation for updating drupal code  with scale-webdev
- [x] instructions for bootstrapping nodes not managed by vagrant.

**Comment by irabinovitch** [comment]
I think we can close this out.
