### ISSUE TITLE
Use firewalld to open port 80 and 443

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/scale-chef#104]
https://github.com/socallinuxexpo/scale-chef/blob/master/cookbooks/scale_apache/recipes/common.rb#L27 tries to open port 80 and 443 via iptables commands, but it looks like CentOS uses firewalld to manage iptables. Thus one needs to instead add the following to the `<zone>` defined in `/etc/firewalld/zones/public.xml`:

```
<port protocol="tcp" port="80"/>
<port protocol="tcp" port="443"/>

```

**Comment by jaymzh** [comment]
We do not use firewalld. we use standard iptables powered by fb_iptables.

**Comment by jaymzh** [comment]
Hmm, but for some reason it's running on reg... that's bizare

**Comment by jaymzh** [comment]
Removed firewalld and reloaded iptables. I'll close this and make a follow up to make sure chef removes firewalld always.
