### ISSUE TITLE
lists-test environment needs work

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-chef#106]
> Most of the lists-test setup is horked.  Took a brief look today as I
> was hoping to upgrade phplist:
>
> 1) chef runs have been failing forever as mailman wont start unless at
> least 1 list exists.  our chef recipes dont create any lists, they
> restore backups of production lists. we probably dont want that in
> test.
>
> 2) test databases dont exist for php list
>
> 3) no credentials for backups/dbs/etc present.

**Comment by jaymzh** [comment]
dropped all the tests stuff
