### ISSUE TITLE
register.socallinuxexpo.org has an invalid cert

### ISSUE THREAD

**Issue by leizleiz** [socallinuxexpo/scale-chef#114]
Issued To:
Common Name (CN)	www.socallinuxexpo.org
Organization (O)	scale

Issued By:
Common Name (CN)	www.socallinuxexpo.org
Organization (O)	scale

Validity Period:
Issued On	Tuesday, July 18, 2017 at 7:29:22 PM
Expires On	Sunday, April 12, 2020 at 7:29:22 PM

**Comment by irabinovitch** [comment]
Looks like its missing the intermediate cert?

**Comment by jaymzh** [comment]
Oh, when I updated the SSL config, reg got missed. Fixing now.
