### ISSUE TITLE
decide on backup retention window

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-chef#36]
To keep s3 bills down we should delete our daily backups after some period of time.  60 days seems reasonable to me. Anyone feel we need longer?

**Comment by irabinovitch** [comment]
Ping? Bill isn't terrible but would be nice to not waste money.

**Comment by leizleiz** [comment]
For backups older than 60 days, keep just 1 / month?

**Comment by jaymzh** [comment]
60 days is plenty. I'm good with monthly for a year, and daily for 30-60 days.

**Comment by irabinovitch** [comment]
Looks like the backup buckets have 90 day expiry on them. 

RDS retaining backups for 30 days.
