### ISSUE TITLE
Access to rackspace

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-chef#68]
Can I please get access to the rackspace UI?

the `scale-web1-test` host needs to be renamed `scale-www-test1`. We need a dev database. I don't think we need a test reg (yet?). Also... in general I should probably have acess.

**Comment by irabinovitch** [comment]
@jaymzh missed this. do you still need access?

**Comment by jaymzh** [comment]
It would indeed be useful.
