### ISSUE TITLE
chef-ify php.ini

### ISSUE THREAD

**Issue by jaymzh** [socallinuxexpo/scale-chef#92]
We've currently bumped the memory limit to 256M from 128M and need to capture this in Chef.

**Comment by irabinovitch** [comment]
Was this on the web server?

**Comment by irabinovitch** [comment]
Looks like we need the following:
- scale-web: set memory higher to allow for larger attachment uploads
- scale-lists: set date.timezone to anything so phplist doesn't complain.

**Comment by irabinovitch** [comment]
manually set this to 20MB to resolve issues speakers were having.  hope we can get it chef'd up eventually
