### ISSUE TITLE
HTTP-> HTTPS redirect for registration

### ISSUE THREAD

**Issue by irabinovitch** [socallinuxexpo/scale-chef#93]
@leizleiz @jaymzh can we get HTTP redirecting to HTTPS on register.socallinuxexpo.org?  I keep having to remind folks to type in HTTPS, which isn't an idea user experience.  1/2 folks reach out to tell me  sponsor registration is "down".

**Comment by leizleiz** [comment]
If you give out a https:// link, shouldn't this be a non-issue?

I can muck around with the configs and see if I can get it to work,but I imagine we need Chef recipe changes to make the changes permanent?

**Comment by irabinovitch** [comment]
Yes I've been giving out HTTPS links but it still appears to be an issue at
times.

**Comment by jaymzh** [comment]
@leizleiz please do not change configs on the box manually... ever. They will be reverted 15 minutes later. The config is in Chef. The READMEs here are good. The apache config in Chef is 1:1 that of the actual files...  I'll probably get around to this on a plan on Friday... but if you can make it work in apache you can send a PR to the cookbooks ;)

**Comment by leizleiz** [comment]
Yes, I know they will be reverted. I suppose I should test elsewhere.

So we need to enable http, and in the http config, add something like:
Redirect permanent / https://register.socallinuxexpo.org/
RewriteEngine on
RewriteCond %{HTTPS} off
RewriteRule (.*) https://register.socallinuxexpo.org$1 [L,R]

**Comment by jaymzh** [comment]
Yeah. we have a shit tonne of those on www already for easy comparison :)

How to test is in the docs.

**Comment by irabinovitch** [comment]
Ping? Anyone able to do this? I realize it should be simple to remember https, but I'm having to ask sponsors to do this 3-4 times a day.

**Comment by jaymzh** [comment]
I'll try to get to it this weekend... I've been out of town for the holidays and have a lot to catch up on...
